SETTING_FILENAME = 'filename'
SETTING_RECENT_FILES = 'recentFiles'
SETTING_WIN_SIZE = 'window/size'
SETTING_WIN_POSE = 'window/position'
SETTING_WIN_GEOMETRY = 'window/geometry'
SETTING_LINE_COLOR = 'line/color'
SETTING_FILL_COLOR = 'fill/color'
SETTING_ADVANCE_MODE = 'advanced'
SETTING_WIN_STATE = 'window/state'
SETTING_SAVE_DIR = 'savedir'
SETTING_PAINT_LABEL = 'paintlabel'
SETTING_LAST_OPEN_DIR = 'lastOpenDir'
SETTING_LAST_WEIGHT_DIR = 'lastWeightDir'
SETTING_LAST_OPEN_IMAGE = 'lastOpenImage'
SETTING_AUTO_SAVE = 'autosave'
SETTING_SINGLE_CLASS = 'singleclass'
SETTING_Magnifying_Lens = "magnifyinglens"
FORMAT_PASCALVOC = 'PascalVOC'
FORMAT_YOLO = 'YOLO'
SETTING_DRAW_SQUARE = 'draw/square'
SETTING_DRAW_MODE = 'draw/mode'
SETTING_YOLO_SAVE_SEG = 'yolo/save_segmentation'
SETTING_AUTOLABEL_DUP_IOU = 'autolabel/dedup_iou'
SETTING_AUTOLABEL_CROSS_CLASS_DEDUP = 'autolabel/cross_class_dedup'
SETTING_AUTOLABEL_WEIGHTS = 'autolabel/weights'
SETTING_AUTOLABEL_CONF = 'autolabel/conf'
SETTING_AUTOLABEL_PRED_IOU = 'autolabel/pred_iou'
SETTING_AUTOLABEL_SETUP_DONE = 'autolabel/setup_done'
# True only after user completes the Auto Label weight picker once (missing in old pkl => force dialog).
SETTING_AUTOLABEL_WEIGHTS_CONFIRMED = 'autolabel/weights_confirmed'
SETTING_FILE_FILTER_SPECIES = 'fileFilter/species'
SETTING_FILE_FILTER_SCORE_ENABLED = 'fileFilter/score_enabled'
SETTING_FILE_FILTER_SCORE_THRESHOLD = 'fileFilter/score_threshold'
SETTING_FILE_FILTER_COUNT_ENABLED = 'fileFilter/count_enabled'
SETTING_FILE_FILTER_COUNT_THRESHOLD = 'fileFilter/count_threshold'
SETTING_AUTO_UPDATE_ENABLED = 'update/auto_check_enabled'
SETTING_UPDATE_MANIFEST_URL = 'update/manifest_url'
SETTING_LAST_UPDATE_CHECK = 'update/last_check'
SETTING_KEYPOINT_TEMPLATE = 'keypoints/template'
SETTING_KEYPOINT_SCHEMA_FILE = 'keypoints/schema_file'
SETTING_MAKE_DATASETS_IMAGE = 'make_datasets/image_dir'
SETTING_MAKE_DATASETS_LABEL = 'make_datasets/label_dir'
SETTING_MAKE_DATASETS_OUTPUT = 'make_datasets/output_dir'
SETTING_MAKE_DATASETS_VOC = 'make_datasets/voc'
SETTING_MAKE_DATASETS_SINGLE_CLASS = 'make_datasets/single_class'
SETTING_MAKE_DATASETS_SINGLE_NAME = 'make_datasets/single_class_name'
SETTING_MAKE_DATASETS_CLASSES_FILE = 'make_datasets/classes_file'
SETTING_MAKE_DATASETS_SPLIT = 'make_datasets/split'
SETTING_MAKE_DATASETS_CREATE_TEST = 'make_datasets/create_test'
SETTING_MAKE_DATASETS_TEST_SPLIT = 'make_datasets/test_split'
SETTING_MAKE_DATASETS_UW_OFFLINE = 'make_datasets/uw_offline'
SETTING_MAKE_DATASETS_UW_COPIES = 'make_datasets/uw_copies'
SETTING_MAKE_DATASETS_UW_STRENGTH = 'make_datasets/uw_strength'
SETTING_UW_OFFLINE_DATASET = 'uw_offline/dataset_root'
SETTING_UW_OFFLINE_COPIES = 'uw_offline/copies'
SETTING_UW_OFFLINE_STRENGTH = 'uw_offline/strength'
SETTING_UW_OFFLINE_SPLIT_TRAIN = 'uw_offline/split_train'
SETTING_UW_OFFLINE_SPLIT_VAL = 'uw_offline/split_val'
SETTING_UW_OFFLINE_SPLIT_TEST = 'uw_offline/split_test'
DEFAULT_ENCODING = 'utf-8'
APP_VERSION = '3.5.1'
APP_UPDATE_DATE = '2026-6-12'
APP_CHANGELOG = [
    'Fix: difficult/score conversion rule (score>0.5→not difficult)',
    'Refactor: Label Self-Refine parameter persistence, mode dropdown, simplified reports',
    'Fix: interactive review now generates unlimited previews for all pending items',
    'Fix: review.html embedded manifest for static mode + server force-rebuild before start',
    'Feat: highlight target box with orange border in review preview images',
    'Fix: review/review action detail now shows class name suggestions',
    'Fix: TensorBoard on Windows uses project base dir for multi-run discovery',
]
